### ISSUE TITLE
Request fails in packaged build for android (Moto G5 S Plus)

### ISSUE THREAD

**Issue by manuganu9** [ufna/VaRest#169]
Hi,
I packaged the android apk and installed on Moto G5 S Plus. When i request the url on button. It always fails.

I also disabled the Verify Peer. But it didn't work.

![capture](https://user-images.githubusercontent.com/7544384/41832278-f35db3f8-7868-11e8-9bd6-eedd5e489446.PNG)

**Comment by ufna** [comment]
Hi @manuganu9 ,

What version of the engine and plugin you're using? Also, please provide logs from build.

**Comment by manuganu9** [comment]
**Plugin Version:**
"Version" : 22,
"VersionName" : "1.1-r22",


**Engine Version:** 4.19.1 Release

**Comment by ufna** [comment]
@manuganu9 Sorry, just checked your comment :(

You're receiveing json not in format you're reding it:

`{"tile_id":"2","user_id":"3","company_id":"1","company_name":"TileViz","tile_name":"0027_LT","texture_image":"TI_5af29fbad1f11.jpg","displacement_map_image":null,"displacement_intensity":"0","specular_map_image":null,"specular_intensity":"0.9","metalic_map_image":null,"metalic_intensity":"0","overlapping_map_image":null,"roughness":"0","visibility_id":"2","main_type":"Wall","type":"Digital Tiles","size":"300X600"}`

Then: 

`[2018.06.28-10.28.00:895][563]LogVaRest: Warning: No field with name displacement_map_image of type String
[2018.06.28-10.28.00:895][563]LogVaRest: Warning: No field with name specular_map_image of type String
[2018.06.28-10.28.00:895][563]LogVaRest: Warning: No field with name metalic_map_image of type String
[2018.06.28-10.28.00:895][563]LogVaRest: Warning: No field with name overlapping_map_image of type String`

Because `"specular_map_image":null` is not a valid string field.
